apiVersion: v1
kind: ConfigMap
metadata:
  name: hd-agent-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: hd-agent-config
    {{- include "hd.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.config }}
  {{- if ne $key "token" }}
  {{- if kindIs "map" $value }}
  {{ $key }}: {{ $value | toJson | quote }}
  {{- else }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}