apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hd-agent-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hd-agent
      app.kubernetes.io/part-of: hybrid-deployment