---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hd-job-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hd.labels" (dict "Values" .Values "name" "hd-job-sa") | nindent 4 }}
  annotations:
    {{- include "hd.annotations" (dict "Values" .Values "annotations" .Values.config.sa_annotations) | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hd-job-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hd.labels" (dict "Values" .Values "name" "hd-job-role") | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["list", "get", "create", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hd-job-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hd.labels" (dict "Values" .Values "name" "hd-job-rolebinding") | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: hd-job-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: hd-job-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hd-agent-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hd.labels" (dict "Values" .Values "name" "hd-agent-sa") | nindent 4 }}
  annotations:
    {{- include "hd.annotations" (dict "Values" .Values "annotations" .Values.config.sa_annotations) | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hd-agent-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hd.labels" (dict "Values" .Values "name" "hd-agent-role") | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list", "create", "delete", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["list"]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "list" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hd-agent-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hd.labels" (dict "Values" .Values "name" "hd-agent-rolebinding") | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: hd-agent-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: hd-agent-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hd-agent-event-reader
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hd.labels" (dict "Values" .Values "name" "hd-agent-event-reader") | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hd-agent-event-reader-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hd.labels" (dict "Values" .Values "name" "hd-agent-event-reader-binding") | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: hd-agent-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: hd-agent-event-reader
  apiGroup: rbac.authorization.k8s.io
