apiVersion: v1
kind: ServiceAccount
{{- include "hd.metadata" (dict 
      "Values" .Values 
      "Release" .Release 
      "name" "hd-job-sa") | nindent 0 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
{{- include "hd.metadata" (dict 
      "Values" .Values 
      "Release" .Release 
      "name" "hd-job-role") | nindent 0 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["list", "get", "create", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
{{- include "hd.metadata" (dict 
      "Values" .Values 
      "Release" .Release 
      "name" "hd-job-rolebinding") | nindent 0 }}
subjects:
  - kind: ServiceAccount
    name: hd-job-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: hd-job-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
{{- include "hd.metadata" (dict 
      "Values" .Values 
      "Release" .Release 
      "name" "hd-agent-sa" 
      "annotations" .Values.config.sa_annotations) | nindent 0 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
{{- include "hd.metadata" (dict 
      "Values" .Values 
      "Release" .Release 
      "name" "hd-agent-role") | nindent 0 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list", "create", "delete", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["list"]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "list" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
{{- include "hd.metadata" (dict 
      "Values" .Values 
      "Release" .Release 
      "name" "hd-agent-rolebinding") | nindent 0 }}
subjects:
  - kind: ServiceAccount
    name: hd-agent-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: hd-agent-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
{{- include "hd.metadata" (dict 
      "Values" .Values 
      "Release" .Release 
      "name" "hd-agent-event-reader") | nindent 0 }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
{{- include "hd.metadata" (dict 
      "Values" .Values 
      "Release" .Release 
      "name" "hd-agent-event-reader-binding") | nindent 0 }}
subjects:
  - kind: ServiceAccount
    name: hd-agent-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: hd-agent-event-reader
  apiGroup: rbac.authorization.k8s.io

