apiVersion: v1
kind: ServiceAccount
metadata:
  # Used by Hybrid Deployment Jobs
  name: hd-job-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: hd-job-sa
    {{- include "hd.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  # Role that will be used by HD jobs
  namespace: {{ .Release.Namespace }}
  name: hd-job-role
  labels:
    app.kubernetes.io/name: hd-job-role
    {{- include "hd.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["list", "get", "create", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hd-job-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: hd-job-rolebinding
    {{- include "hd.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: hd-job-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: hd-job-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  # Used by Hybrid Deployment Agent
  name: hd-agent-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: hd-agent-sa
    {{- include "hd.labels" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  # Role used by HD Agent
  namespace: {{ .Release.Namespace }}
  name: hd-agent-role
  labels:
    app.kubernetes.io/name: hd-agent-role
    {{- include "hd.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list", "create", "delete", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["list"]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "list" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hd-agent-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: hd-agent-rolebinding
    {{- include "hd.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: hd-agent-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: hd-agent-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: hd-agent-event-reader
  labels:
    app.kubernetes.io/name: hd-agent-event-reader
    {{- include "hd.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hd-agent-event-reader-binding
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: hd-agent-event-reader-binding
    {{- include "hd.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: hd-agent-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: hd-agent-event-reader
  apiGroup: rbac.authorization.k8s.io

