image: "us-docker.pkg.dev/prod-eng-fivetran-ldp/public-docker-us/ldp-agent:production"
image_pull_policy: "Always"

config:
  data_volume_pvc: 
  token: # (Insecure) Use caution when specifying the token in plaintext, do not commit the token to Git
  token_secret_ref: # (More secure) The name of an existing Kubernetes Secret containing a key named 'agent-token' whose value is the token. When set, config.token will be ignored.

labels: {}
node_selector: {}
tolerations: []

agent:
  resources:
    requests:
      cpu: "2000m"
      memory: "2Gi"
    limits:
      cpu: "4000m"
      memory: "4Gi"
