on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'V*' # Push events to matching V*, i.e. V1.0, V20.15.10

name: Create release

permissions:
  contents: write

jobs:
  release_and_changelogs:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes

  release_helm_chart:
    name: Release helm chart
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Use gcloud CLI
        run: gcloud info

      - name: Use gcloud components update
        run: gcloud components update

      - name: Use gcloud configure-docker
        run: gcloud auth configure-docker us-east1-docker.pkg.dev

      - name: Install helm
        run: curl -s -L https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Package chart
        run: cd agent && /usr/local/bin/helm package .

      - name: Push packaged chart to local-dev
        run: cd agent && /usr/local/bin/helm push *.tgz oci://us-docker.pkg.dev/fivetran-wild-west/local-dev/helm

      - name: Push packaged chart to public-docker-us
        run: cd agent && /usr/local/bin/helm push *.tgz oci://us-docker.pkg.dev/prod-eng-fivetran-ldp/public-docker-us/helm
